// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSiniestros.Data.Context;

#nullable disable

namespace MiniSiniestros.Data.Migrations.Migrations
{
    [DbContext(typeof(MiniSiniestrosDbContext))]
    [Migration("20260821144836_AddNotificacionSRT")]
    partial class AddNotificacionSRT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSiniestros.Entities.Empleador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.ToTable("Empleadores", (string)null);
                });

            modelBuilder.Entity("MiniSiniestros.Entities.NotificacionSRT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiniestroId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SiniestroId");

                    b.ToTable("NotificacionesSRT", (string)null);
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Prestador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Prestadores", (string)null);
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Siniestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SiniestroEstadoId")
                        .HasColumnType("int");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadorId");

                    b.HasIndex("SiniestroEstadoId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("Siniestros", (string)null);
                });

            modelBuilder.Entity("MiniSiniestros.Entities.SiniestroEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SiniestroEstados", (string)null);
                });

            modelBuilder.Entity("MiniSiniestros.Entities.SiniestroEstadoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiniestroEstadoId")
                        .HasColumnType("int");

                    b.Property<int>("SiniestroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiniestroEstadoId");

                    b.HasIndex("SiniestroId");

                    b.ToTable("SiniestroEstadoHistoriales", (string)null);
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Siniestro_Prestador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<int>("SiniestroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.HasIndex("SiniestroId");

                    b.ToTable("SiniestroPrestadores", (string)null);
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EmpleadorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadorId");

                    b.ToTable("Trabajadores", (string)null);
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("MiniSiniestros.Entities.NotificacionSRT", b =>
                {
                    b.HasOne("MiniSiniestros.Entities.Siniestro", "Siniestro")
                        .WithMany()
                        .HasForeignKey("SiniestroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Siniestro");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Siniestro", b =>
                {
                    b.HasOne("MiniSiniestros.Entities.Empleador", "Empleador")
                        .WithMany()
                        .HasForeignKey("EmpleadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSiniestros.Entities.SiniestroEstado", "SiniestroEstado")
                        .WithMany()
                        .HasForeignKey("SiniestroEstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSiniestros.Entities.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleador");

                    b.Navigation("SiniestroEstado");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.SiniestroEstadoHistorial", b =>
                {
                    b.HasOne("MiniSiniestros.Entities.SiniestroEstado", "SiniestroEstado")
                        .WithMany()
                        .HasForeignKey("SiniestroEstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSiniestros.Entities.Siniestro", "Siniestro")
                        .WithMany()
                        .HasForeignKey("SiniestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siniestro");

                    b.Navigation("SiniestroEstado");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Siniestro_Prestador", b =>
                {
                    b.HasOne("MiniSiniestros.Entities.Prestador", "Prestador")
                        .WithMany()
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSiniestros.Entities.Siniestro", "Siniestro")
                        .WithMany()
                        .HasForeignKey("SiniestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");

                    b.Navigation("Siniestro");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Trabajador", b =>
                {
                    b.HasOne("MiniSiniestros.Entities.Empleador", "Empleador")
                        .WithMany()
                        .HasForeignKey("EmpleadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleador");
                });
#pragma warning restore 612, 618
        }
    }
}
