<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniSiniestros.Common\MiniSiniestros.Common.csproj" />
    <ProjectReference Include="..\MiniSiniestros.Data\MiniSiniestros.Data.csproj" />
    <ProjectReference Include="..\MiniSiniestros.Dto\MiniSiniestros.Dto.csproj" />
    <ProjectReference Include="..\MiniSiniestros.Models\MiniSiniestros.Entities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Polly" Version="8.4.1" />
  </ItemGroup>

</Project>
